### ISSUE TITLE
データフロー変更に伴うバグ潰し

### ISSUE THREAD

**Issue by qh73xe** [kikuchiken-waseda/mri-vuewer.ver2#25]
## 概要
データ追加が上手く行かない例が存在する問題を修正するために,
解析データ処理時のデータフローを簡素化した.

この簡素化の影響で以下の動作がおかしくなっているので修正する

### 高優先度
- [x] ファイル検索: メタデータ検索が映らない
- [x] 全般: ダウンロード動作が実施されない
- [x] フレーム更新時: 時間遷移時に画像が更新されないことがある
- [x] 転記階層選択: バックスペース, delete が動作しない
- [x] 転記階層選択: クリック系の挿入動作が行われない
- [x] 転記層選択: Ctrl Shift k イベントティアの動作がおかしい
- [x] フレーム転記時: パレットによる色指定が動作しない
- [x] ルーラー: 画像情報がわたされない

### 中優先度

- [x] 全般: ノイズ除去動作が実施されない
- [x] フレーム更新時: 開始終了フレーム時の他箇所参照がおかしい.
- [x] 転記階層選択: ctrl + , ctrl - キーが動作しない
- [x] フレーム転記時: 点群，矩形制約がフレームをいって帰ってくると外れる

### 低優先度
- [ ] 転記層選択: ^ ~ の動作が日本語キーボード対応していない
- [x] 全般: 入力欄のマイクは反応しない

**Comment by qh73xe** [comment]
全般: ダウンロード動作が実施されない に関しては問題の本質がStore の複雑化に来ていることに注意.
現状動画関連の情報は current/index.js にも current/video.js にも挿入されておりそれぞれが自由に参照しているので，
責任範囲を区分すべき．

**Comment by qh73xe** [comment]
転記層選択: Ctrl Shift k イベントティアの動作がおかしい に関しては Linux では確認されない．

**Comment by qh73xe** [comment]
ルーラーに関しては後日復旧を前提に一時停止

**Comment by tsuyo-pon** [comment]
from 吉永
# バグ取り作業について
-------------------
## 高優先度について
フレーム更新時: 時間遷移時に画像が更新されないことがある．
- すみません．何のことを指しているのか分かりませんでした．
- *相談後，確認*

転記階層選択: バックスペース, delete が動作しない
- バックスペース, delete が動作しないことを確認
- *要修正*

転記層選択: Ctrl Shift k イベントティアの動作がおかしい
- Ctrl Shift j は動くけど，Ctrl Shift k は動かない．
- *要修正*

-------------------

## 中優先度
全般: ノイズ除去動作が実施されない
- しばらく時間がかかったのちに，普通に表示される
- 聞いてもスペクトログラムを見ても音が変わった(ノイズ除去された)感じはしない．
- *要確認*

フレーム更新時: 開始終了フレーム時の他箇所参照がおかしい.
- 終了を参照した際は大丈夫そうだが，開始を参照する際が未解決．
- 終了を参照した際に，左フレームは終了の一個前，中央フレームは終了，右フレームは終了フレームが表示されている．
- 開始を参照した際に，左フレームは参照前の画像，中央フレームは開始，右フレームは開始の一個後が表示されている．
- *要修正*

転記層選択: Ctrl +, Ctrl - キーが動作しない
- Ctrl Shift - キーで拡大を確認
- Ctrl - キーで縮小を確認
- 想定していた動作なのかはわからない
- *要確認*

**Comment by qh73xe** [comment]
- [ ] 転記階層選択: バックスペース, delete が動作しない [delete のみの場合に削除されない]

**Comment by qh73xe** [comment]
16 文字がTIERの限界？
