### ISSUE TITLE
ティアが削除されない

### ISSUE THREAD

**Issue by tsuyo-pon** [kikuchiken-waseda/mri-vuewer.ver2#29]
## 問題
TIER 削除ダイアログで複数選択を行った際にTIERが削除されず，
一括削除が出来無いので不便

## 現象
アプリケーションボタンから、ティアを削除する場合について
- ティアを選択せずに削除ボタンを押すと、何も削除できない。

**Comment by qh73xe** [comment]
## TODO
- [ ] 一括削除時のTIER選択動作を確認
- [ ] TIER削除関数の実施条件を変更

**Comment by qh73xe** [comment]
ローカル環境では削除が上手くいくことを確認．
